### ISSUE TITLE
Github Discussion

### ISSUE THREAD

**Issue by jgarte** [stefan-hoeck/idris2-tutorial#62]
Hi,

What do you think of enabling GitHub Discussions so we can discuss aspects of the book and ask general questions without opening an issue for it?

**Comment by stefan-hoeck** [comment]
That's a great idea. I didn't know about GitHub Discussions. Will read about and enable it over the next couple of days. If I forget to do so, a quick reminder would be welcome.

**Comment by jgarte** [comment]
Closing as completed. @stefan-hoeck Thank you!
